// src/lib/features/Home/Services.tsx
"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowUpRight } from "lucide-react";
import { cn } from "@/utils/utils";

const SERVICES = [
   {
      id: "01",
      title: "Web Development",
      description: "We specialize in developing dynamic, responsive, and scalable web applications tailored to your business needs.",
   },
   {
      id: "02",
      title: "Mobile App Development",
      description: "Our mobile experts create intuitive and powerful applications for iOS and Android, ensuring a seamless user experience across all devices.",
   },
   {
      id: "03",
      title: "UI/UX Development",
      description: "We design beautiful, functional, and user-centered interfaces that enhance engagement and provide a delightful journey for your customers.",
   },
   {
      id: "04",
      title: "Maintenance",
      description: "Stay worry-free with our comprehensive maintenance services, including regular updates, bug fixes, and performance optimizations.",
   },
   {
      id: "05",
      title: "IT Consultation",
      description: "Leverage our technical expertise to navigate complex IT challenges and develop a roadmap that aligns with your long-term vision.",
   },
   {
      id: "06",
      title: "Security",
      description: "Protect your digital assets with our rigorous security protocols and audits, ensuring your data and users are safe from emerging threats.",
   },
];

export default function Services() {
   const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);

   return (
      <section className="py-24 bg-(--brand-parchment) overflow-hidden">
         <div className="main-container">
            {/* Heading Section */}
            <div className="text-center mb-28">
               <h2 className="text-4xl md:text-6xl lg:text-7xl font-bold text-(--brand-primary) tracking-tighter leading-[1.1] uppercase">
                  OUR EXPERTISE GOES<br /> BEYOND DESIGN
               </h2>
            </div>

            {/* Services List Root */}
            <div className="relative border-t border-(--brand-text-main)/20">
               {SERVICES.map((service, index) => (
                  <motion.div
                     key={service.id}
                     onMouseEnter={() => setHoveredIndex(index)}
                     onMouseLeave={() => setHoveredIndex(null)}
                     className={cn(
                        "group relative border-b border-(--brand-text-main)/20 transition-all duration-500",
                        hoveredIndex === index ? "bg-(--brand-primary)" : "bg-transparent"
                     )}
                  >
                     <div className="relative z-20 flex px-2 py-10 md:py-16 cursor-pointer">
                        {/* 12-Column Grid Simulation */}
                        <div className="grid grid-cols-12 w-full items-center gap-4">

                           {/* Sequence Part (Col 1) */}
                           <div className="col-span-1 hidden md:block">
                              <span className={cn(
                                 "text-xs font-semibold font-mono transition-colors duration-500",
                                 hoveredIndex === index ? "text-(--brand-parchment)/60" : "text-(--brand-text-main)/40"
                              )}>
                                 ({service.id})
                              </span>
                           </div>

                           {/* Title Part (Col 2-5) */}
                           <div className="col-span-12 md:col-span-4 pl-4 md:pl-0">
                              <h3 className={cn(
                                 "text-4xl md:text-5xl lg:text-6xl font-medium tracking-tight transition-colors duration-500",
                                 hoveredIndex === index ? "text-(--brand-parchment)" : "text-(--brand-text-main)"
                              )}>
                                 {service.title}
                              </h3>
                           </div>

                           {/* Description Part (Col 6-11) */}
                           <div className="col-span-11 md:col-span-6 md:col-start-6 mt-4 md:mt-0 transition-all duration-500">
                              <p className={cn(
                                 "text-sm md:text-base leading-relaxed transition-colors duration-500 max-w-lg",
                                 hoveredIndex === index ? "text-(--brand-parchment)/90" : "text-(--brand-text-muted)"
                              )}>
                                 {service.description}
                              </p>
                           </div>

                           {/* Arrow Part (Col 12) */}
                           <div className="col-span-1 flex justify-end pr-4">
                              <div className={cn(
                                 "transition-all duration-500 transform",
                                 hoveredIndex === index ? "opacity-100 translate-x-0 scale-110" : "opacity-0 -translate-x-8 scale-50"
                              )}>
                                 <ArrowUpRight className="w-8 h-8 md:w-10 md:h-10 text-(--brand-parchment)" strokeWidth={1.5} />
                              </div>
                           </div>

                        </div>
                     </div>

                     {/* Centered Floating Image Background Effect */}
                     <AnimatePresence>
                        {hoveredIndex === index && (
                           <motion.div
                              initial={{ opacity: 0, scale: 0.7, y: 30 }}
                              animate={{
                                 opacity: 1,
                                 scale: 1,
                                 y: [0, -15, 0], // Continuous floating
                              }}
                              exit={{ opacity: 0, scale: 0.7, y: 30 }}
                              transition={{
                                 opacity: { duration: 0.4 },
                                 scale: { duration: 0.5, ease: [0.16, 1, 0.3, 1] },
                                 y: {
                                    duration: 4,
                                    repeat: Infinity,
                                    ease: "easeInOut"
                                 }
                              }}
                              className="absolute inset-0 z-0 pointer-events-none flex items-center justify-center overflow-hidden"
                           >

                           </motion.div>
                        )}
                     </AnimatePresence>
                  </motion.div>
               ))}
            </div>
         </div>
      </section>
   );
}

// app/components/sections/Services.vue
<script setup lang="ts">
import webDevImg from '~/assets/web-dev.png'


const services = [
  {
    name: 'Web Development',
    badges: ['WEB APPLICATION', 'FRONT-END DEVELOPMENT', 'WEB PORTAL', 'SINGLE PAGE APPLICATION'],
    description: 'We specialize in developing dynamic, responsive, and scalable web applications tailored to your business needs.',
    image: webDevImg,
  },
  {
    name: 'Mobile App Development',
    badges: ['iOS', 'ANDROID', 'CROSS-PLATFORM', 'REACT NATIVE'],
    description: 'We build high-performance mobile applications for iOS and Android that deliver seamless user experiences.',
    image: webDevImg,
  },
  {
    name: 'UI/UX Development',
    badges: ['FIGMA', 'PROTOTYPING', 'USER RESEARCH', 'DESIGN SYSTEMS'],
    description: 'We craft intuitive and visually compelling interfaces that enhance user engagement and satisfaction.',
    image: webDevImg,
  },
  {
    name: 'Maintenance',
    badges: ['BUG FIXES', 'PERFORMANCE', 'UPDATES', 'MONITORING'],
    description: 'We provide ongoing support and maintenance to keep your digital products running smoothly and securely.',
    image: webDevImg,
  },
  {
    name: 'IT Consultation',
    badges: ['STRATEGY', 'ARCHITECTURE', 'TECH STACK', 'ROADMAP'],
    description: 'We help businesses make smart technology decisions with expert consultation tailored to your goals.',
    image: webDevImg,
  },
  {
    name: 'Security',
    badges: ['AUDITS', 'PENETRATION TESTING', 'COMPLIANCE', 'SSL'],
    description: 'We protect your digital assets with comprehensive security assessments and implementation.',
    image: webDevImg,
  },
]

const activeIndex = ref(0)
const isAnimating = ref(false)

function selectService(i: number) {
  if (i === activeIndex.value) return
  isAnimating.value = true
  setTimeout(() => {
    activeIndex.value = i
    isAnimating.value = false
  }, 250)
}

const active = computed(() => services[activeIndex.value])
</script>

<template>
  <section id="what-we-do" class="py-20 md:py-28">
    <div class="mx-auto max-w-7xl px-6">

      <SectionTitle label="Services We Provide" class="mb-4" />

      <p class="font-normal mb-14 max-w-2xl" style="font-size: 20px; color: rgb(152,151,151);">
        We realize that every business is unique and has its own set of requirements.
        That's why we offer customized web development
      </p>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20 items-start">

        <!-- Left: image — updates with fade animation -->
        <div class="flex justify-center lg:justify-start order-2 lg:order-1">
          <Transition name="fade">
            <img
              :key="activeIndex"
              :src="active?.image"
              :alt="active?.name"
              class="w-full max-w-[420px] object-contain"
            />
          </Transition>
        </div>

        <!-- Right: active service info + service list -->
        <div class="order-1 lg:order-2 flex flex-col gap-8">

          <!-- Active service details — fades on change -->
          <div
            class="transition-opacity duration-250"
            :class="isAnimating ? 'opacity-0' : 'opacity-100'"
          >
            <!-- Active title with teal gradient -->
            <h3
              class="font-semibold mb-5 leading-tight"
              style="font-size: clamp(32px, 3.5vw, 48px); background: linear-gradient(to right, #059584, #b4fff6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;"
            >
              {{ active?.name }}
            </h3>

            <!-- Badges -->
            <div class="flex flex-wrap gap-3 mb-5">
              <span
                v-for="badge in active?.badges"
                :key="badge"
                class="px-4 py-2 rounded-full text-sm font-normal"
                style="background-color: rgb(217,217,217); color: rgb(74,74,74); font-size: 16px;"
              >
                {{ badge }}
              </span>
            </div>

            <!-- Description -->
            <p class="font-normal leading-relaxed" style="font-size: 20px; color: rgb(0,0,0);">
              {{ active?.description }}
            </p>
          </div>

          <!-- Divider -->
          <hr class="border-neutral-200" />

          <!-- Other services list -->
          <div class="flex flex-col gap-1">
            <button
              v-for="(service, i) in services"
              :key="i"
              class="text-left py-3 font-semibold transition-colors duration-200 border-b border-neutral-100 last:border-0"
              :style="{
                fontSize: 'clamp(22px, 2.5vw, 36px)',
                color: i === activeIndex ? 'transparent' : 'rgb(91,91,91)',
                background: i === activeIndex
                  ? 'linear-gradient(to right, #059584, #b4fff6)'
                  : 'none',
                WebkitBackgroundClip: i === activeIndex ? 'text' : 'unset',
                backgroundClip: i === activeIndex ? 'text' : 'unset',
                WebkitTextFillColor: i === activeIndex ? 'transparent' : 'rgb(91,91,91)',
              }"
              @click="selectService(i)"
            >
              {{ service.name }}
            </button>
          </div>

        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.25s ease, transform 0.25s ease;
}
.fade-enter-from {
  opacity: 0;
  transform: translateY(10px);
}
.fade-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
.fade-leave-active {
  position: absolute;
}
</style>
